mixed-port: 7890
allow-lan: false
unified-delay: true
tcp-concurrent: true
log-level: info
bind-address: "*"
find-process-mode: always
global-client-fingerprint: chrome
keep-alive-interval: 15
keep-alive-idle: 600
experimental:
  quic-go-disable-gso: true
external-ui-name: zashboard
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  override-destination: false
  force-dns-mapping: true
  parse-pure-ip: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - tls://223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fake-ip-filter:
    - "*"
    - +.lan
    - +.local
    - time.*.com
    - ntp.*.com
    - +.market.xiaomi.com
  use-hosts: false
  use-system-hosts: false
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
